CREATE TABLE [dbo].[FactTicketSeat_V2]
(
[SaleDate] [date] NULL,
[SaleTime] [time] NULL,
[SaleDateTime] [datetime] NULL,
[TicketingAccountId] [int] NULL,
[DimArenaId] [int] NOT NULL,
[ArenaCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArenaName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeasonHeaderId] [int] NOT NULL,
[SeasonHeaderCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderYear] [int] NULL,
[SeasonHeaderIsActive] [bit] NULL,
[DimSeasonId] [int] NOT NULL,
[SeasonName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonYear] [int] NULL,
[SeasonClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sport] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimEventHeaderId] [int] NOT NULL,
[EventHeaderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHeaderDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHeaderDate] [date] NULL,
[EventHeaderTime] [time] NULL,
[EventHeaderDateTime] [datetime] NULL,
[EventHeaderOpenTime] [datetime] NULL,
[EventHeaderFinishTime] [datetime] NULL,
[EventSeasonNumber] [int] NULL,
[EventHeaderHomeNumber] [int] NULL,
[EventHeaderGameNumber] [int] NULL,
[EventLevel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GameType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimEventId] [int] NOT NULL,
[EventCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventDate] [date] NULL,
[EventTime] [time] NULL,
[EventDateTime] [datetime] NULL,
[EventClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MajorCategoryTM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinorCategoryTM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimItemId] [int] NULL,
[ItemCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemPlanOrEvent] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPlanId] [int] NULL,
[PlanCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanFSE] [decimal] (18, 6) NULL,
[PlanType] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanEventCnt] [int] NULL,
[DimPriceCodeId] [int] NULL,
[PriceCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC4] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceCodeDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceCodeGroup] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeatId] [int] NOT NULL,
[SectionName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seat] [int] NULL,
[SeatLocationMapping] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatLevelName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimTicketClassId] [int] NULL,
[TicketClassCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketClassName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimTicketTypeId] [int] NULL,
[TicketTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPlanTypeId] [int] NULL,
[PlanTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanTypeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeatTypeId] [int] NULL,
[SeatTypeCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatTypeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSeatStatusId] [int] NULL,
[ClassName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistStatus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimSalesCodeId] [int] NULL,
[SalesCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesCodeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimPromoId] [int] NULL,
[PromoCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManifestedPriceCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManifestedClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManifestedSeatValue] [decimal] (18, 6) NULL,
[PostedPriceCode] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostedClassName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostedSeatValue] [decimal] (18, 6) NULL,
[HeldPriceCode] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeldClassName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeldSeatValue] [decimal] (18, 6) NULL,
[IsSaleable] [bit] NULL,
[IsAvailable] [bit] NULL,
[IsHeld] [bit] NULL,
[IsReserved] [bit] NOT NULL,
[IsSold] [bit] NULL,
[IsHost] [bit] NOT NULL,
[IsComp] [bit] NOT NULL,
[TM_comp_code] [int] NULL,
[TM_comp_name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPremium] [bit] NOT NULL,
[IsSingleEvent] [bit] NOT NULL,
[IsPlan] [bit] NOT NULL,
[IsPartial] [bit] NOT NULL,
[IsGroup] [bit] NOT NULL,
[IsRenewal] [bit] NOT NULL,
[IsBroker] [bit] NOT NULL,
[TotalRevenue] [decimal] (38, 20) NULL,
[PurchasePrice] [decimal] (18, 6) NULL,
[PcTicketValue] [decimal] (18, 6) NULL,
[Surcharge] [decimal] (18, 6) NULL,
[PcTicket] [decimal] (18, 6) NULL,
[PcTax] [decimal] (18, 6) NULL,
[PcLicenseFee] [decimal] (18, 6) NULL,
[PcOther1] [decimal] (18, 6) NULL,
[PcOther2] [decimal] (18, 6) NULL,
[IsAttended] [bit] NULL,
[ScanDateTime] [datetime] NULL,
[ScanGate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtySeat] [int] NOT NULL,
[QtySeatFSE] [decimal] (38, 20) NULL,
[PaidAmount] [decimal] (18, 6) NULL,
[OwedAmount] [decimal] (18, 6) NULL,
[OrderNum] [bigint] NULL,
[OrderLineItem] [int] NULL,
[RetailTicketType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailQualifiers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsResold] [bit] NULL,
[ResoldDimTicketCustomerId] [bigint] NULL,
[ResoldDimCustomerId] [bigint] NULL,
[ResoldCustomerId] [int] NULL,
[ResoldCustomerName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Resold_CRMContactId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResoldDateTime] [datetime] NULL,
[ResoldPurchasePrice] [decimal] (29, 17) NULL,
[ResoldFees] [decimal] (29, 17) NULL,
[ResoldTotalAmount] [decimal] (29, 17) NULL,
[SalesSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupSalesName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchticsAddUser] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustomerIdSalesRep] [int] NULL,
[DimCustomerId_TransSalesRep] [int] NULL,
[SSID_event_id] [int] NULL,
[SSID_section_id] [int] NULL,
[SSID_row_id] [int] NULL,
[SSID_seat] [int] NULL,
[config_isCapacityEligible] [bit] NULL,
[IsPair] [bit] NULL,
[DimTicketCustomerId] [int] NULL,
[CustomerId] [int] NULL,
[DimCustomerId] [bigint] NULL,
[CustomerName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRMContactId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimRepId] [int] NULL,
[AccountRep] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_TM_section_id] [int] NULL,
[ETL__SSID_TM_row_id] [int] NULL,
[ETL__SSID_TM_seat] [int] NULL,
[FactInventoryId] [bigint] NULL,
[FactTicketSalesId] [bigint] NULL,
[FactAttendanceId] [bigint] NULL,
[FactTicketActivityId_Resold] [bigint] NULL,
[FactTicketActivityId_Tranferred] [bigint] NULL,
[FactAvailSeatsId] [bigint] NULL,
[FactHeldSeatsId] [bigint] NULL,
[ETL__CreatedDate] [datetime] NULL
)
GO
