CREATE TABLE [ods].[Aramark_CheckHeader]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__Aramark_C__ETL_C__498EEC8D] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__Aramark_C__ETL_U__4A8310C6] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__Aramark_C__ETL_I__4B7734FF] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_FileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemID] [int] NULL,
[SiteID] [int] NULL,
[SystemPOSID] [int] NULL,
[locationID] [int] NULL,
[revenueCenterID] [int] NULL,
[revenueCenterPOSRef] [int] NULL,
[guestcheckId] [int] NULL,
[orderTypePOSRef] [int] NULL,
[checkNum] [int] NULL,
[openBusinessDate] [datetime] NULL,
[closeBusinessDate] [datetime] NULL,
[openDatetime] [datetime] NULL,
[closeDatetime] [datetime] NULL,
[numGuests] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checkRef] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checkTotal] [decimal] (11, 2) NULL,
[taxTotal] [decimal] (11, 2) NULL,
[taxExempt] [decimal] (11, 2) NULL,
[voidTotal] [decimal] (11, 2) NULL,
[tipTotal] [decimal] (11, 2) NULL,
[managerVoidTotal] [decimal] (11, 2) NULL,
[returnTotal] [decimal] (11, 2) NULL,
[errorCorrectTotal] [decimal] (11, 2) NULL,
[xferStatus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[xferToCheckNum] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serviceChargeTotal] [decimal] (11, 2) NULL,
[discountTotal] [decimal] (11, 2) NULL,
[subTotal] [decimal] (11, 2) NULL,
[tax1total] [decimal] (11, 2) NULL,
[tax2total] [decimal] (11, 2) NULL,
[tax3total] [decimal] (11, 2) NULL,
[tax4total] [decimal] (11, 2) NULL,
[tax5total] [decimal] (11, 2) NULL,
[tax6total] [decimal] (11, 2) NULL,
[tax7total] [decimal] (11, 2) NULL,
[tax8total] [decimal] (11, 2) NULL,
[revenueCenterName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ods].[Aramark_CheckHeader] ADD CONSTRAINT [PK__Aramark___7EF6BFCD8D5970ED] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
